
spring:
  jpa:
    show-sql: false
    open-in-view: false
    
  mongodb:
    embedded:
      version: 4.0.21

  security:
    user:
      name: user
      password: secret
      
logging:
  level:
    '[org.springframework.security]': debug
    
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    health:
      show-details: always             
---
spring:
  config:
    activate:
      on-profile:
      - prod
  datasource:
    url: jdbc:postgresql://localhost:5432/member-documents
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      connection-timeout: 2000
    
  jpa:
    hibernate:
      ddl-auto: validate
      